### ISSUE TITLE
Add fedmsg for #help and #halp

### ISSUE THREAD

**Issue by nirik** [fedora-infra/supybot-fedmsg#8]
Meetbot allows you to do "#help we need someone to frob the gnarthle" in a meeting and the output shows that the group was looking for help with that item. 

It would be good to fedmsg those, then perhaps collect them all weekly in a cron script and mail devel list with a 'list of things people need help with' and links to the meetbot meeting it was asked in.

**Comment by ralphbean** [comment]
We've been talking about replacing meetbot with a new consolidated version, or replacing supybot with something else all-together.  I'm going to punt on this one and just wait until we get either of those questions figured out (so we don't accumulate technical debt in supybot-fedmsg).

**Comment by mattdm** [comment]
Sounds good. Let's make sure not to lose this suggestion, though.

**Comment by decause** [comment]
Now that there is http://whatcanidoforfedora.org, it would be great if there were a pipeline to get items added during a meeting with <code>#halp</code> to then get a ticket somewhere, that then shows up on fedmsg, and then gets assimilated into wcidff.org?

A ticket may or may not be a good intermediary, and I'm open to suggestions.

**Comment by ralphbean** [comment]
This looks like it's going to be really easy:

```diff
diff --git a/supybot-fedmsg/plugin.py b/supybot-fedmsg/plugin.py
index 67321ae..a2c4c3b 100644
--- a/supybot-fedmsg/plugin.py
+++ b/supybot-fedmsg/plugin.py
@@ -80,6 +80,16 @@ class Injector(threading.Thread):
             'do_startmeeting': 'meeting.start',
             'do_endmeeting': 'meeting.complete',
             'do_topic': 'meeting.topic.update',
+
+            'do_agreed':    'meeting.agreed',
+            'do_accepted':  'meeting.accepted',
+            'do_rejected':  'meeting.rejected',
+
+            'do_action':    'meeting.action',
+            'do_info':      'meeting.info',
+            'do_idea':      'meeting.idea',
+            'do_help':      'meeting.help',  # This is also "halp"
+            'do_link':      'meeting.link',
         }
         for target_method, topic in tap_points.items():
 
```

**Comment by mattdm** [comment]
I think we probably want the meeting items to age out of wherever they're displayed; they're not quite like the longer-term, more stable "get involved" pages for SIGs and other groups....
